language: java
sudo: required
jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=LATEST-TRUNK-SNAPSHOT
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=IC-2017.3 # Stable
  - IDEA_VERSION=IC-2017.2 # Previous
  - IDEA_VERSION=IC-2017.1 # Old
